# Generated by Django 5.1 on 2024-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employee_em_status_33d5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company_id'], name='employee_em_company_e18daf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_em_departm_26167f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employee_em_positio_e45583_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location'], name='employee_em_locatio_038dc5_idx'),
        ),
    ]
