# Generated by Django 5.1 on 2024-08-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_company_columns_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(choices=[('New York', 'New York'), ('San Francisco', 'San Francisco'), ('Singapore', 'Singapore')], max_length=50),
        ),
    ]
