# Generated by Django 5.1 on 2024-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(choices=[('new_york', 'New York'), ('san_francisco', 'San Francisco'), ('singapore', 'Singapore')], max_length=50),
        ),
    ]
